### ISSUE TITLE
Publish Cloud Native Maturity Model on CNCF Website

### ISSUE THREAD

**Issue by siforster** [cncf/cartografos#46]
Investigate getting the cloud native maturity model published on the CNCF website.
A relevant section could be the "Community" Section, near the "Cloud Native Glossary".
Part of the this project may include
* Wireframing the model
* Relevant graphic design
* Liaison with the CNCF Web Team

**Comment by daniellemcook** [comment]
To mirror this doc: https://docs.google.com/document/d/1_NQe97i-gwDPo8erhg7JoxZExWTX8cxpFTHXCXqxVz0/edit#heading=h.7jqduiootbv3

**Comment by siforster** [comment]
Will be based on similar hugo template to https://contribute.cncf.io/resources

**Comment by cjyabraham** [comment]
I have set up [the Maturity Model site](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/) ready for your feedback. Let me know what you think. Also, could I get some content for [the homepage](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/), the [About](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/about/), and [Contribute](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/contribute/) pages? What do you want to say there?

**Comment by siforster** [comment]
Hi Chris,
Thanks for setting this up - it looks really great even in preview!


We have a prologue document which would be a good candidate for the homepage.
You can find it here:
https://github.com/cncf/cartografos/blob/main/reference/prologue.md

For About, I would suggest just the content of the README.md for now.
Finally, we also have a contributors page in the Repo: https://github.com/cncf/cartografos/blob/website/CONTRIBUTING.md
I would suggest as a placeholder, something like the first three sections:
* Introduction
* Contributing
* Come to meetings

I've had a look through the branch you've created, website, and for updates, would we just add commits into the respective `./website/content/*` directory?  Or alternatively is there a different process we would use for updating?

This is a great start, thank you!

Simon

**Comment by cjyabraham** [comment]
Ok, I've adapted [the prologue docs](https://github.com/cncf/cartografos/blob/main/reference/prologue.md) to fit [the homepage](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/) and inserted a couple of images. Feel free to suggest other images if you'd prefer. The ones I picked are from [the CNCF flickr account](https://www.flickr.com/photos/143247548@N03/albums).

I've adapted [the readme](https://github.com/cncf/cartografos/blob/main/README.md) for [the About page](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/about/).

I've adapted [the CONTRIBUTING.md file](https://github.com/cncf/cartografos/blob/website/CONTRIBUTING.md) for [the Contribute page](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/contribute/). I've added a [Contributing to the Website](https://deploy-preview-47--sprightly-peony-c62818.netlify.app/contribute/#contributing-to-the-website) section to the bottom. 

Yes, going forward, you'll be able to just edit the content files yourself and anyone from the community could submit a PR. If you're happy with the approach for this, should we merge this `website` PR into `main` and then I can get it set up on the maturitymodel.cncf.io domain? We can continue to refine things there until we're ready to promote it properly?

**Comment by siforster** [comment]
Hi Chris,

Thank you for updating the home page and the about page as well.  They look really good.  Thanks also for retining your own content about how to test out the website.  This is very helpful.

Yes, let's merge `website` into `main` and set it up on maturitymodel.cncf.io.  We have a community meeting coming up on Tuesday the 10th of February and I expect then that we'll get more feedback from the group.

We can continue to refine prior to promoting properly as you suggest.

Thank you!

**Comment by caniszczyk** [comment]
can we also make the alias cnmm.cncf.io point to maturitymodel.cncf.io?

Thanks!

**Comment by siforster** [comment]
Terrific, thank you very much for this, Chris!

We have a community meeting tomorrow at 1pm US Eastern, and I expect we will get further feedback tomorrow.
It looks really amazing - thank you for your effort so far!

**Comment by cjyabraham** [comment]
The site is now up on https://maturitymodel.cncf.io/
Also cnmm.cncf.io redirects to it.

We've also now got a social share image so that is looks like this on twitter:
<img width="583" alt="Screen Shot 2023-01-11 at 10 38 48 AM" src="https://user-images.githubusercontent.com/463160/211712258-ff54a93a-e20d-4730-867f-03d9f511bd86.png">

**Comment by siforster** [comment]
Hi Chris, this is great!  It looks really terrific and both the urls work great for me.
Thank you for your effort on this, it is terrific and we look forward to publicising it.

We have some updates in progress and if we have any problems we will get in touch.

Thanks again!

**Comment by siforster** [comment]
The maturity model has now been published at maturitymodel.cncf.io (also cnmm.cncf.io)

**Comment by cjyabraham** [comment]
hi @siforster, keep me posted on when you'd like the site linked in to the CNCF.io megamenu.

**Comment by siforster** [comment]
Hi @cjyabraham, thank you.
I've started a thread on [slack](https://cloud-native.slack.com/archives/C026EQ8LU2Z/p1676396524288689) about this, and I expect it to be an agenda topic at the next community meeting.

Related to the website, a contributor has made submitted a small PR https://github.com/cncf/cartografos/pull/52 which Netlify has not been able to render.  Would you be able to investigate?  Many thanks!

**Comment by cjyabraham** [comment]
@siforster it looks like the netlify build didn't proceed because there was no change to the code of the site and so there would be nothing to preview. The PR only changes the README.md of the repo.

**Comment by siforster** [comment]
@cjyabraham Thanks Chris!  I think I missed the wood for the trees!  Merged!  Thank you!

**Comment by kumarankit999** [comment]
Why is this issue still Opened!
Is there anything we missing out!

**Comment by siforster** [comment]
Model published at maturitymodel.cncf.io
