### ISSUE TITLE
Do we want feedback buttons on pages of the site?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cartografos#67]
I've recently got the page feedback buttons to work on the [CNCF Glossary site](https://glossary.cncf.io/abstraction/) (see at the bottom of the page). They feed events into our cncf.io Google Analytics 4 property which we can later create reports on to see which pages get good feedback, which do not.

<img src="https://github.com/cncf/cartografos/assets/463160/71e21b1f-90ad-44a3-acca-063619fb4adc" width=400>

Would we like this feature activating for the Maturity Model site? If not, please just close this issue.

**Comment by siforster** [comment]
Hi Chris,

Thank you for this!
Doe the form allow comments in the feedback, and also would we get the chance to see the reports?
I see real value in getting to see some of this feedback including areas for improvement.

Many thanks,

Simon

**Comment by cjyabraham** [comment]
Hi @siforster, the form currently doesn't allow for comments, however, people can leave an issue about a particular page using the "Create Issue" link in the right sidebar. I have not developed the reports yet but once I gather some data, I can see what's possible using Google Analytics.

**Comment by cjyabraham** [comment]
Ok, I've deployed the buttons. Let's wait a few weeks and see if we gather any useful data.
