### ISSUE TITLE
Feedback link missing on model overview (main page)

### ISSUE THREAD

**Issue by krumware** [cncf/cartografos#69]
I'm adding this using the feedback function from the level pages (looks great!)
However, I didn't see an option on the overview (main page). That could be intentional, but there is a lot of really great content there, so I wanted to upvote having a feedback link on that page as well.

**Comment by kumarankit999** [comment]
It will be more beneficial if you can refer here to the Site link where this issue happens. Thanks for contributing here!

**Comment by krumware** [comment]
This is the page I'm referring to: https://maturitymodel.cncf.io/

**Comment by siforster** [comment]
Hi @cjyabraham,

Would it be possible to have the feedback function available on the front page of https://maturitymodel.cncf.io/ to allow readers to comment please?

Many thanks!

**Comment by cjyabraham** [comment]
Generally the feedback buttons aren't put on the homepage of sites since that page isn't usually the type of informative page you'd want feedback on. In the case of the Maturity Model, however, it does contain a ton of info so makes sense to add it there.

**Comment by cjyabraham** [comment]
Here is in [this PR](https://github.com/cncf/cartografos/pull/70), ready for merging.
